version: '3'

tasks:
  hello:
    cmds:
      - echo 'Hello World from Task!'
    silent: true

  worker1:
    cmds:
      - cargo watch --ignore 'worker*' -x 'r --bin worker -- --port=3001 --rpc-port=50051 --name=worker1'

  worker2:
    cmds:
      - cargo watch --ignore 'worker*' -x 'r --bin worker -- --port=3002 --rpc-port=50052 --name=worker2'

  worker3:
    cmds:
      - cargo watch --ignore 'worker*' -x 'r --bin worker -- --port=3003 --rpc-port=50053 --name=worker3'

  server:
    cmds:
      - cargo watch --ignore 'worker*' -x 'r --bin server -- --port=3000'

  redis:
    cmds:
      - docker run --name my-redis -p 6379:6379 --restart always --detach redis

  consul:
    dir: /
    cmds:
      - consul agent -data-dir=/tmp/consul -dev