version: '3'

tasks:
  hello:
    cmds:
      - echo 'Hello World from Task!'
    silent: true

  worker1:
    cmds:
      - cargo watch --ignore 'worker*' -x 'r --bin worker -- --port=3001 --name=worker1'

  worker2:
    cmds:
      - cargo watch --ignore 'worker*' -x 'r --bin worker -- --port=3002 --name=worker2'

  server:
    cmds:
      - cargo watch --ignore 'worker*' -x 'r --bin server -- --port=3000'

  redis:
    cmds:
      - docker run --name my-redis -p 6379:6379 --restart always --detach redis